/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TreinamentosNrRouteImport } from './routes/treinamentos-nr'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProtecaoEmpresarialSstRouteImport } from './routes/protecao-empresarial-sst'
import { Route as PgrRouteImport } from './routes/pgr'
import { Route as PerguntasFrequentesRouteImport } from './routes/perguntas-frequentes'
import { Route as PcmsoRouteImport } from './routes/pcmso'
import { Route as Nr1RiscosPsicossociaisRouteImport } from './routes/nr-1-riscos-psicossociais'
import { Route as MedicinaDoTrabalhoRouteImport } from './routes/medicina-do-trabalho'
import { Route as LaudosRouteImport } from './routes/laudos'
import { Route as FrancaSpRouteImport } from './routes/franca-sp'
import { Route as EsocialSstRouteImport } from './routes/esocial-sst'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as CasosRouteImport } from './routes/casos'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AreaDoClienteRouteImport } from './routes/area-do-cliente'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminCategoriasRouteImport } from './routes/admin.categorias'
import { Route as AdminBlogRouteImport } from './routes/admin.blog'
import { Route as AdminAutoresRouteImport } from './routes/admin.autores'
import { Route as AdminBlogNovoRouteImport } from './routes/admin.blog.novo'
import { Route as AdminBlogEditarIdRouteImport } from './routes/admin.blog.editar.$id'

const TreinamentosNrRoute = TreinamentosNrRouteImport.update({
  id: '/treinamentos-nr',
  path: '/treinamentos-nr',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtecaoEmpresarialSstRoute = ProtecaoEmpresarialSstRouteImport.update({
  id: '/protecao-empresarial-sst',
  path: '/protecao-empresarial-sst',
  getParentRoute: () => rootRouteImport,
} as any)
const PgrRoute = PgrRouteImport.update({
  id: '/pgr',
  path: '/pgr',
  getParentRoute: () => rootRouteImport,
} as any)
const PerguntasFrequentesRoute = PerguntasFrequentesRouteImport.update({
  id: '/perguntas-frequentes',
  path: '/perguntas-frequentes',
  getParentRoute: () => rootRouteImport,
} as any)
const PcmsoRoute = PcmsoRouteImport.update({
  id: '/pcmso',
  path: '/pcmso',
  getParentRoute: () => rootRouteImport,
} as any)
const Nr1RiscosPsicossociaisRoute = Nr1RiscosPsicossociaisRouteImport.update({
  id: '/nr-1-riscos-psicossociais',
  path: '/nr-1-riscos-psicossociais',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicinaDoTrabalhoRoute = MedicinaDoTrabalhoRouteImport.update({
  id: '/medicina-do-trabalho',
  path: '/medicina-do-trabalho',
  getParentRoute: () => rootRouteImport,
} as any)
const LaudosRoute = LaudosRouteImport.update({
  id: '/laudos',
  path: '/laudos',
  getParentRoute: () => rootRouteImport,
} as any)
const FrancaSpRoute = FrancaSpRouteImport.update({
  id: '/franca-sp',
  path: '/franca-sp',
  getParentRoute: () => rootRouteImport,
} as any)
const EsocialSstRoute = EsocialSstRouteImport.update({
  id: '/esocial-sst',
  path: '/esocial-sst',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const CasosRoute = CasosRouteImport.update({
  id: '/casos',
  path: '/casos',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AreaDoClienteRoute = AreaDoClienteRouteImport.update({
  id: '/area-do-cliente',
  path: '/area-do-cliente',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCategoriasRoute = AdminCategoriasRouteImport.update({
  id: '/admin/categorias',
  path: '/admin/categorias',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/admin/blog',
  path: '/admin/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAutoresRoute = AdminAutoresRouteImport.update({
  id: '/admin/autores',
  path: '/admin/autores',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBlogNovoRoute = AdminBlogNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => AdminBlogRoute,
} as any)
const AdminBlogEditarIdRoute = AdminBlogEditarIdRouteImport.update({
  id: '/editar/$id',
  path: '/editar/$id',
  getParentRoute: () => AdminBlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/area-do-cliente': typeof AreaDoClienteRoute
  '/blog': typeof BlogRouteWithChildren
  '/casos': typeof CasosRoute
  '/contato': typeof ContatoRoute
  '/esocial-sst': typeof EsocialSstRoute
  '/franca-sp': typeof FrancaSpRoute
  '/laudos': typeof LaudosRoute
  '/medicina-do-trabalho': typeof MedicinaDoTrabalhoRoute
  '/nr-1-riscos-psicossociais': typeof Nr1RiscosPsicossociaisRoute
  '/pcmso': typeof PcmsoRoute
  '/perguntas-frequentes': typeof PerguntasFrequentesRoute
  '/pgr': typeof PgrRoute
  '/protecao-empresarial-sst': typeof ProtecaoEmpresarialSstRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/treinamentos-nr': typeof TreinamentosNrRoute
  '/admin/autores': typeof AdminAutoresRoute
  '/admin/blog': typeof AdminBlogRouteWithChildren
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/blog/novo': typeof AdminBlogNovoRoute
  '/admin/blog/editar/$id': typeof AdminBlogEditarIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/area-do-cliente': typeof AreaDoClienteRoute
  '/blog': typeof BlogRouteWithChildren
  '/casos': typeof CasosRoute
  '/contato': typeof ContatoRoute
  '/esocial-sst': typeof EsocialSstRoute
  '/franca-sp': typeof FrancaSpRoute
  '/laudos': typeof LaudosRoute
  '/medicina-do-trabalho': typeof MedicinaDoTrabalhoRoute
  '/nr-1-riscos-psicossociais': typeof Nr1RiscosPsicossociaisRoute
  '/pcmso': typeof PcmsoRoute
  '/perguntas-frequentes': typeof PerguntasFrequentesRoute
  '/pgr': typeof PgrRoute
  '/protecao-empresarial-sst': typeof ProtecaoEmpresarialSstRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/treinamentos-nr': typeof TreinamentosNrRoute
  '/admin/autores': typeof AdminAutoresRoute
  '/admin/blog': typeof AdminBlogRouteWithChildren
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/blog/novo': typeof AdminBlogNovoRoute
  '/admin/blog/editar/$id': typeof AdminBlogEditarIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/area-do-cliente': typeof AreaDoClienteRoute
  '/blog': typeof BlogRouteWithChildren
  '/casos': typeof CasosRoute
  '/contato': typeof ContatoRoute
  '/esocial-sst': typeof EsocialSstRoute
  '/franca-sp': typeof FrancaSpRoute
  '/laudos': typeof LaudosRoute
  '/medicina-do-trabalho': typeof MedicinaDoTrabalhoRoute
  '/nr-1-riscos-psicossociais': typeof Nr1RiscosPsicossociaisRoute
  '/pcmso': typeof PcmsoRoute
  '/perguntas-frequentes': typeof PerguntasFrequentesRoute
  '/pgr': typeof PgrRoute
  '/protecao-empresarial-sst': typeof ProtecaoEmpresarialSstRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/treinamentos-nr': typeof TreinamentosNrRoute
  '/admin/autores': typeof AdminAutoresRoute
  '/admin/blog': typeof AdminBlogRouteWithChildren
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/blog/novo': typeof AdminBlogNovoRoute
  '/admin/blog/editar/$id': typeof AdminBlogEditarIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/area-do-cliente'
    | '/blog'
    | '/casos'
    | '/contato'
    | '/esocial-sst'
    | '/franca-sp'
    | '/laudos'
    | '/medicina-do-trabalho'
    | '/nr-1-riscos-psicossociais'
    | '/pcmso'
    | '/perguntas-frequentes'
    | '/pgr'
    | '/protecao-empresarial-sst'
    | '/sitemap.xml'
    | '/sobre'
    | '/treinamentos-nr'
    | '/admin/autores'
    | '/admin/blog'
    | '/admin/categorias'
    | '/admin/dashboard'
    | '/admin/login'
    | '/blog/$slug'
    | '/admin/'
    | '/admin/blog/novo'
    | '/admin/blog/editar/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/area-do-cliente'
    | '/blog'
    | '/casos'
    | '/contato'
    | '/esocial-sst'
    | '/franca-sp'
    | '/laudos'
    | '/medicina-do-trabalho'
    | '/nr-1-riscos-psicossociais'
    | '/pcmso'
    | '/perguntas-frequentes'
    | '/pgr'
    | '/protecao-empresarial-sst'
    | '/sitemap.xml'
    | '/sobre'
    | '/treinamentos-nr'
    | '/admin/autores'
    | '/admin/blog'
    | '/admin/categorias'
    | '/admin/dashboard'
    | '/admin/login'
    | '/blog/$slug'
    | '/admin'
    | '/admin/blog/novo'
    | '/admin/blog/editar/$id'
  id:
    | '__root__'
    | '/'
    | '/area-do-cliente'
    | '/blog'
    | '/casos'
    | '/contato'
    | '/esocial-sst'
    | '/franca-sp'
    | '/laudos'
    | '/medicina-do-trabalho'
    | '/nr-1-riscos-psicossociais'
    | '/pcmso'
    | '/perguntas-frequentes'
    | '/pgr'
    | '/protecao-empresarial-sst'
    | '/sitemap.xml'
    | '/sobre'
    | '/treinamentos-nr'
    | '/admin/autores'
    | '/admin/blog'
    | '/admin/categorias'
    | '/admin/dashboard'
    | '/admin/login'
    | '/blog/$slug'
    | '/admin/'
    | '/admin/blog/novo'
    | '/admin/blog/editar/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AreaDoClienteRoute: typeof AreaDoClienteRoute
  BlogRoute: typeof BlogRouteWithChildren
  CasosRoute: typeof CasosRoute
  ContatoRoute: typeof ContatoRoute
  EsocialSstRoute: typeof EsocialSstRoute
  FrancaSpRoute: typeof FrancaSpRoute
  LaudosRoute: typeof LaudosRoute
  MedicinaDoTrabalhoRoute: typeof MedicinaDoTrabalhoRoute
  Nr1RiscosPsicossociaisRoute: typeof Nr1RiscosPsicossociaisRoute
  PcmsoRoute: typeof PcmsoRoute
  PerguntasFrequentesRoute: typeof PerguntasFrequentesRoute
  PgrRoute: typeof PgrRoute
  ProtecaoEmpresarialSstRoute: typeof ProtecaoEmpresarialSstRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreRoute: typeof SobreRoute
  TreinamentosNrRoute: typeof TreinamentosNrRoute
  AdminAutoresRoute: typeof AdminAutoresRoute
  AdminBlogRoute: typeof AdminBlogRouteWithChildren
  AdminCategoriasRoute: typeof AdminCategoriasRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/treinamentos-nr': {
      id: '/treinamentos-nr'
      path: '/treinamentos-nr'
      fullPath: '/treinamentos-nr'
      preLoaderRoute: typeof TreinamentosNrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protecao-empresarial-sst': {
      id: '/protecao-empresarial-sst'
      path: '/protecao-empresarial-sst'
      fullPath: '/protecao-empresarial-sst'
      preLoaderRoute: typeof ProtecaoEmpresarialSstRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pgr': {
      id: '/pgr'
      path: '/pgr'
      fullPath: '/pgr'
      preLoaderRoute: typeof PgrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perguntas-frequentes': {
      id: '/perguntas-frequentes'
      path: '/perguntas-frequentes'
      fullPath: '/perguntas-frequentes'
      preLoaderRoute: typeof PerguntasFrequentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pcmso': {
      id: '/pcmso'
      path: '/pcmso'
      fullPath: '/pcmso'
      preLoaderRoute: typeof PcmsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nr-1-riscos-psicossociais': {
      id: '/nr-1-riscos-psicossociais'
      path: '/nr-1-riscos-psicossociais'
      fullPath: '/nr-1-riscos-psicossociais'
      preLoaderRoute: typeof Nr1RiscosPsicossociaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medicina-do-trabalho': {
      id: '/medicina-do-trabalho'
      path: '/medicina-do-trabalho'
      fullPath: '/medicina-do-trabalho'
      preLoaderRoute: typeof MedicinaDoTrabalhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laudos': {
      id: '/laudos'
      path: '/laudos'
      fullPath: '/laudos'
      preLoaderRoute: typeof LaudosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/franca-sp': {
      id: '/franca-sp'
      path: '/franca-sp'
      fullPath: '/franca-sp'
      preLoaderRoute: typeof FrancaSpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esocial-sst': {
      id: '/esocial-sst'
      path: '/esocial-sst'
      fullPath: '/esocial-sst'
      preLoaderRoute: typeof EsocialSstRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casos': {
      id: '/casos'
      path: '/casos'
      fullPath: '/casos'
      preLoaderRoute: typeof CasosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/area-do-cliente': {
      id: '/area-do-cliente'
      path: '/area-do-cliente'
      fullPath: '/area-do-cliente'
      preLoaderRoute: typeof AreaDoClienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/categorias': {
      id: '/admin/categorias'
      path: '/admin/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof AdminCategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/admin/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/autores': {
      id: '/admin/autores'
      path: '/admin/autores'
      fullPath: '/admin/autores'
      preLoaderRoute: typeof AdminAutoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/blog/novo': {
      id: '/admin/blog/novo'
      path: '/novo'
      fullPath: '/admin/blog/novo'
      preLoaderRoute: typeof AdminBlogNovoRouteImport
      parentRoute: typeof AdminBlogRoute
    }
    '/admin/blog/editar/$id': {
      id: '/admin/blog/editar/$id'
      path: '/editar/$id'
      fullPath: '/admin/blog/editar/$id'
      preLoaderRoute: typeof AdminBlogEditarIdRouteImport
      parentRoute: typeof AdminBlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface AdminBlogRouteChildren {
  AdminBlogNovoRoute: typeof AdminBlogNovoRoute
  AdminBlogEditarIdRoute: typeof AdminBlogEditarIdRoute
}

const AdminBlogRouteChildren: AdminBlogRouteChildren = {
  AdminBlogNovoRoute: AdminBlogNovoRoute,
  AdminBlogEditarIdRoute: AdminBlogEditarIdRoute,
}

const AdminBlogRouteWithChildren = AdminBlogRoute._addFileChildren(
  AdminBlogRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AreaDoClienteRoute: AreaDoClienteRoute,
  BlogRoute: BlogRouteWithChildren,
  CasosRoute: CasosRoute,
  ContatoRoute: ContatoRoute,
  EsocialSstRoute: EsocialSstRoute,
  FrancaSpRoute: FrancaSpRoute,
  LaudosRoute: LaudosRoute,
  MedicinaDoTrabalhoRoute: MedicinaDoTrabalhoRoute,
  Nr1RiscosPsicossociaisRoute: Nr1RiscosPsicossociaisRoute,
  PcmsoRoute: PcmsoRoute,
  PerguntasFrequentesRoute: PerguntasFrequentesRoute,
  PgrRoute: PgrRoute,
  ProtecaoEmpresarialSstRoute: ProtecaoEmpresarialSstRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreRoute: SobreRoute,
  TreinamentosNrRoute: TreinamentosNrRoute,
  AdminAutoresRoute: AdminAutoresRoute,
  AdminBlogRoute: AdminBlogRouteWithChildren,
  AdminCategoriasRoute: AdminCategoriasRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
